### ISSUE TITLE
pickling memoryviews doesn't work

### ISSUE THREAD

**Issue by pitrou** [cloudpipe/cloudpickle#77] opened 2017-01-26 21:38 UTC
This is on Python 3.5. It seems cloudpickle tries to support memoryviews (the traceback shows a dedicated `save_memoryview` method, but fails:
```
>>> import cloudpickle
>>> m = memoryview(b"abc")
>>> cloudpickle.dumps(m)
Traceback (most recent call last):
  File "<ipython-input-3-c69575090534>", line 1, in <module>
    cloudpickle.dumps(m)
  File "/home/antoine/miniconda3/envs/dask35/lib/python3.5/site-packages/cloudpickle/cloudpickle.py", line 706, in dumps
    cp.dump(obj)
  File "/home/antoine/miniconda3/envs/dask35/lib/python3.5/site-packages/cloudpickle/cloudpickle.py", line 146, in dump
    return Pickler.dump(self, obj)
  File "/home/antoine/miniconda3/envs/dask35/lib/python3.5/pickle.py", line 408, in dump
    self.save(obj)
  File "/home/antoine/miniconda3/envs/dask35/lib/python3.5/pickle.py", line 475, in save
    f(self, obj) # Call unbound method with explicit self
  File "/home/antoine/miniconda3/envs/dask35/lib/python3.5/site-packages/cloudpickle/cloudpickle.py", line 154, in save_memoryview
    Pickler.save_string(self, str(obj))
AttributeError: type object '_Pickler' has no attribute 'save_string'
```

**Comment by serhiy-storchaka** [comment] 2017-04-04 18:41
Looks as a duplicate of #59.

**Comment by llllllllll** [comment] 2017-05-31 00:21
closing to dedup the issue

**Closed by llllllllll** 2017-05-31 00:21 UTC
Labels: bug
