### ISSUE TITLE
Issue deserializing scikit learn pipeline on Docker using cloudpickle

### ISSUE THREAD

**Issue by gsvijayraajaa** [cloudpipe/cloudpickle#83] opened 2017-04-21 04:29 UTC
#Hi,

I had serialized a pipeline using cloudpickle. When I try to load it inside a docker container, I get the below error;

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/pickle.py", line 1378, in load
    return Unpickler(file).load()
  File "/usr/lib/python2.7/pickle.py", line 858, in load
    dispatch[key](self)
  File "/usr/lib/python2.7/pickle.py", line 1246, in load_build
    for k, v in slotstate.items():
AttributeError: 'mtrand.RandomState' object has no attribute 'items'
```
Load seems to work on the same environment / host. It doesnt load in docker container running python 2.7.

I am using python2.7 , cloudpickle==0.2.2

**Comment by gsvijayraajaa** [comment] 2017-04-21 04:30
Similar issue in dill : https://github.com/uqfoundation/dill/issues/226

**Comment by pitrou** [comment] 2017-05-31 18:39
Are you using the same Python and Numpy versions on the host and inside the container? If no, that could very well be the cause of your issues.

**Comment by ogrisel** [comment] 2017-11-17 10:26
@gsvijayraajaa it's very likely that you are not running the same version of numpy in your container. Let me close this issue. Feel free to reopen if you reproduce the error with the same version of numpy, scikit-learn and python in all environments.

**Closed by ogrisel** 2017-11-17 10:26 UTC
