### ISSUE TITLE
Fail to (un)pickle class with abc.ABCMeta metaclass (python 2.7)

### ISSUE THREAD

**Issue by AmatanHead** [cloudpipe/cloudpickle#103] opened 2017-07-01 06:20 UTC
Hello!

The current code from the master branch fails to work with classes that have the `abc.ABCMeta` metaclass.

MWE:

```python
class Q(object):
    __metaclass__ = abc.ABCMeta

q = Q()
cloudpickle.loads(cloudpickle.dumps(q))
```

With python 2.7.3 this yields:

```
object.__new__(getset_descriptor) is not safe, use getset_descriptor.__new__()
```

With python 2.7.13:

```
TypeError: can't pickle wrapper_descriptor objects
```

**Comment by llllllllll** [comment] 2017-07-01 07:05
This probably broke with #102, ping @ssanderson

**Comment by ssanderson** [comment] 2017-07-01 19:55
@llllllllll I think this was broken before #102.  I tried rolling back and hit a RecursionError with the following test:

```python
    def test_abc(self):
        class AbstractClass(metaclass=abc.ABCMeta):
            pass

        result = pickle_depickle(AbstractClass())
```

**Comment by ssanderson** [comment] 2017-07-01 20:39
The root issue here is actually that ABCMeta uses WeakSet for caching.  Should be fixed by https://github.com/cloudpipe/cloudpickle/pull/104.

**Comment by ssanderson** [comment] 2017-07-01 21:48
@AmatanHead I can't reproduce the exact error from your initial post, but ABCMeta instances generally seem to be working on https://github.com/cloudpipe/cloudpickle/pull/104 if you want to give it a try.

**Comment by AmatanHead** [comment] 2017-07-01 21:58
Wow! That was blazingly fast and it works! Thanks a lot!

**Closed** 2017-07-01 22:49 UTC
Labels: bug
