### ISSUE TITLE
cannot always reliably pickle bob.io.video.reader 

### ISSUE THREAD

**Issue by 183amir** [cloudpipe/cloudpickle#363] opened 2020-04-29 19:42 UTC
I have some problem pickling a function that uses `bob.io.video.reader`  (It's a C++ class wrapped for Python, implementation here: https://gitlab.idiap.ch/bob/bob.io.video/-/blob/master/bob/io/video/reader.cpp)

The steps below allows you to reproduce my issue:
```sh
conda create -n test -c https://www.idiap.ch/software/bob/conda bob.io.video cloudpickle
conda activate test
conda list # see output below
python
```

<details><summary>conda list output</summary>
<p>

```
conda list
# packages in environment at /home/amir/miniconda/envs/test:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main    defaults
blas                      1.0                         mkl    defaults
bob.blitz                 2.0.20           py37h568732d_0    https://www.idiap.ch/software/bob/conda
bob.core                  2.2.4            py37h61c8b34_0    https://www.idiap.ch/software/bob/conda
bob.extension             4.0.0            py37h06b427b_0    https://www.idiap.ch/software/bob/conda
bob.io.base               3.0.7            py37hd5c6fa5_0    https://www.idiap.ch/software/bob/conda
bob.io.video              3.0.2            py37h67c8010_0    https://www.idiap.ch/software/bob/conda
boost                     1.67.0                   py37_4    defaults
bzip2                     1.0.8                h7b6447c_0    defaults
ca-certificates           2020.1.1                      0    defaults
certifi                   2020.4.5.1               py37_0    defaults
click                     7.1.1                      py_0    defaults
click-plugins             1.1.1                      py_0    defaults
cloudpickle               1.3.0                      py_0    defaults
ffmpeg                    4.0                  hf6c5f75_2    https://www.idiap.ch/software/bob/conda
freetype                  2.9.1                h8a8886c_1    defaults
hdf5                      1.10.2               hba1933b_1    defaults
icu                       58.2                 he6710b0_3    defaults
intel-openmp              2020.0                      166    defaults
jpeg                      9b                   h024ee3a_2    defaults
ld_impl_linux-64          2.33.1               h53a641e_7    defaults
libblitz                  1.0.1                hf484d3e_1    https://www.idiap.ch/software/bob/conda
libboost                  1.67.0               h46d08c1_4    defaults
libedit                   3.1.20181209         hc058e9b_0    defaults
libffi                    3.2.1                hd88cf55_4    defaults
libgcc-ng                 9.1.0                hdf63c60_0    defaults
libgfortran-ng            7.3.0                hdf63c60_0    defaults
libopus                   1.3.1                h7b6447c_0    defaults
libpng                    1.6.37               hbc83047_0    defaults
libstdcxx-ng              9.1.0                hdf63c60_0    defaults
libtiff                   4.1.0                h2733197_0    defaults
libvpx                    1.7.0                h439df22_0    defaults
mkl                       2020.0                      166    defaults
mkl-service               2.3.0            py37he904b0f_0    defaults
mkl_fft                   1.0.15           py37ha843d7b_0    defaults
mkl_random                1.1.0            py37hd6b4f25_0    defaults
ncurses                   6.2                  he6710b0_1    defaults
numpy                     1.18.1           py37h4f9e942_0    defaults
numpy-base                1.18.1           py37hde5b4d6_1    defaults
olefile                   0.46                     py37_0    defaults
openh264                  1.7.0                hf6c5f75_2    https://www.idiap.ch/software/bob/conda
openssl                   1.1.1g               h7b6447c_0    defaults
pillow                    7.0.0            py37hb39fc2d_0    defaults
pip                       20.0.2                   py37_1    defaults
py-boost                  1.67.0           py37h04863e7_4    defaults
python                    3.7.7           hcf32534_0_cpython    defaults
readline                  8.0                  h7b6447c_0    defaults
setuptools                46.1.3                   py37_0    defaults
six                       1.14.0                   py37_0    defaults
sqlite                    3.31.1               h62c20be_1    defaults
tk                        8.6.8                hbc83047_0    defaults
wheel                     0.34.2                   py37_0    defaults
xz                        5.2.5                h7b6447c_0    defaults
zlib                      1.2.11               h7b6447c_3    defaults
zstd                      1.3.7                h0b5b093_0    defaults
```

</p>
</details>

```python
>>> import bob.io.video
>>> import cloudpickle
>>> cloudpickle.loads(cloudpickle.dumps(bob.io.video.reader)) # it's ok that it fails
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/amir/miniconda/envs/test/lib/python3.7/site-packages/cloudpickle/cloudpickle.py", line 1334, in _rehydrate_skeleton_class
    setattr(skeleton_class, attrname, attr)
TypeError: can't set attributes of built-in/extension type 'reader'
>>> def load_video(path):
...     return bob.io.video.reader(path).load()
... 
>>> cloudpickle.loads(cloudpickle.dumps(load_video)) # good
<function load_video at 0x7f96ccb74a70>
>>> from bob.io.video import reader
>>> def load_video(path):
...     return reader(path).load()
... 
>>> cloudpickle.loads(cloudpickle.dumps(load_video)) # not good! This is the issue!
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/amir/miniconda/envs/test/lib/python3.7/site-packages/cloudpickle/cloudpickle.py", line 1334, in _rehydrate_skeleton_class
    setattr(skeleton_class, attrname, attr)
TypeError: can't set attributes of built-in/extension type 'reader'
>>> import pickle
>>> pickle.loads(pickle.dumps(bob.io.video.reader)) # it's ok that this fails
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
_pickle.PicklingError: Can't pickle <class 'reader'>: attribute lookup reader on builtins failed
>>> pickle.loads(pickle.dumps(load_video)) # python's pickle works here!
<function load_video at 0x7f96ccb7b170>
```
As you can see I can pickle the `load_video` function only when I use `bob.io.video.reader` inside it. When I use `reader` which was imported like `from bob.io.video import reader`. It doesn't work.

**Comment by ogrisel** [comment] 2020-05-04 08:25
I do not understand why you say that it's ok that it fails on the first example:

```python
>>> import bob.io.video
>>> import cloudpickle
>>> cloudpickle.loads(cloudpickle.dumps(bob.io.video.reader)) # it's ok that it fails
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/amir/miniconda/envs/test/lib/python3.7/site-packages/cloudpickle/cloudpickle.py", line 1334, in _rehydrate_skeleton_class
    setattr(skeleton_class, attrname, attr)
TypeError: can't set attributes of built-in/extension type 'reader'
```

This is the cause of all the other problems from what I see.

Furthermore, this problem also happens with the `pickle` module from the standard library:

```python
>>> import pickle
>>> pickle.loads(pickle.dumps(bob.io.video.reader))                                                                                                                             
Traceback (most recent call last):
  File "<ipython-input-11-5ee69089c17a>", line 1, in <module>
    pickle.loads(pickle.dumps(bob.io.video.reader))
PicklingError: Can't pickle <class 'reader'>: attribute lookup reader on builtins failed
```

I see no reason why this class would not be picklable by the standard library: it's statically defined in an importable module, not a dynamically defined class.

cloudpickle is only meant to extend pickle to support dynamically or locally-defined functions, classes, enums and lambda expressions.

So please report the regular pickle error (the one triggered by `pickle.dumps(bob.io.video.reader)`) to the `bob.io.video` project. The Python wrapping logic for this C++ probably has to be fixed to make the reader class picklable. I am not C++ wrapper expert but I am pretty sure that the problem comes from the fact that at the moment:

```python
>>> bob.io.video.reader.__module__
'builtins'
```

while it should obviously be:

```python
>>> bob.io.video.reader.__module__
'bob.io.video'
```

**Comment by ogrisel** [comment] 2020-05-04 08:29
Closing this as this cannot be fixed in cloudpickle.

**Closed by ogrisel** 2020-05-04 08:29 UTC

**Comment by 183amir** [comment] 2020-05-04 09:41
Thank you for investigating this. I'll report this issue in `bob.io.video`.

**Comment by 183amir** [comment] 2020-05-04 18:24
For reference: https://gitlab.idiap.ch/bob/bob.io.video/-/merge_requests/19
