### ISSUE TITLE
Failing tests in 1.1 for python 3.x

### ISSUE THREAD

**Issue by toddrme2178** [cloudpipe/cloudpickle#49] opened 2016-01-19 09:55 UTC
Hi.  I am trying to package cloudpickle for openSUSE, with unit tests to make sure everything is working properly.  The unit tests works fine for python 2.x (2.6 and 2.7), but the unit tests fail for all versions of Python 3.x (3.3, 3.4 and 3.5).  The packages are identical besides being python 2.x or python 3.x.  All stated dependencies are included, and as near as I can tell my test invocation shouldn't have any substantial differences to how your travis tests are invoked.  Here are the failures (this is for python 3.4, but identical failures occur in 3.3 and 3.5):

```
======================================================================
ERROR: test_pickling_special_file_handles (tests.cloudpickle_file_test.CloudPickleFileTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/abuild/rpmbuild/BUILD/cloudpickle-0.1.1/tests/cloudpickle_file_test.py", line 102, in test_pickling_special_file_handles
    self.assertEquals(out, pickle.loads(cloudpickle.dumps(out)))
  File "/home/abuild/rpmbuild/BUILD/cloudpickle-0.1.1/cloudpickle/cloudpickle.py", line 602, in dumps
    cp.dump(obj)
  File "/home/abuild/rpmbuild/BUILD/cloudpickle-0.1.1/cloudpickle/cloudpickle.py", line 107, in dump
    return Pickler.dump(self, obj)
  File "/usr/lib64/python3.4/pickle.py", line 412, in dump
    self.save(obj)
  File "/usr/lib64/python3.4/pickle.py", line 479, in save
    f(self, obj) # Call unbound method with explicit self
  File "/home/abuild/rpmbuild/BUILD/cloudpickle-0.1.1/cloudpickle/cloudpickle.py", line 548, in save_file
    raise pickle.PicklingError("Cannot pickle files that do not map to an actual file")
_pickle.PicklingError: Cannot pickle files that do not map to an actual file

======================================================================
ERROR: test_temp_file (tests.cloudpickle_file_test.CloudPickleFileTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/abuild/rpmbuild/BUILD/cloudpickle-0.1.1/tests/cloudpickle_file_test.py", line 96, in test_temp_file
    newfile = pickle.loads(cloudpickle.dumps(f))
  File "/home/abuild/rpmbuild/BUILD/cloudpickle-0.1.1/cloudpickle/cloudpickle.py", line 602, in dumps
    cp.dump(obj)
  File "/home/abuild/rpmbuild/BUILD/cloudpickle-0.1.1/cloudpickle/cloudpickle.py", line 107, in dump
    return Pickler.dump(self, obj)
  File "/usr/lib64/python3.4/pickle.py", line 412, in dump
    self.save(obj)
  File "/usr/lib64/python3.4/pickle.py", line 499, in save
    rv = reduce(self.proto)
TypeError: cannot serialize '_io.BufferedRandom' object
```

**Comment by ogrisel** [comment] 2016-01-19 10:01
I cannot reproduce this on the current master (running `tox` in the root of the source folder).

**Comment by toddrme2178** [comment] 2016-01-20 09:09
The problem seems to be with the pypi package.  I downloaded the 0.1.1 pypi package on a completely different system (windows with anaconda) and the test fails the same way.  Then I downloaded 0.1.1 from github and it worked fine.  So there must be something different or missing from the pypi package that is leading to the errors.

**Comment by ogrisel** [comment] 2016-01-20 09:16
Thanks for the report. Which package did you download on PyPI, the source tarball or the wheel archive? It might be the case that we made a mistake when generating the wheel if the PyPI tarball works.

**Comment by toddrme2178** [comment] 2016-01-20 18:12
It was the source tarball, and the zip file on github in the "releases" section.

**Comment by QuLogic** [comment] 2017-02-26 10:35
I haven't tried out the GitHub release yet, but the PyPI 0.2.2 tarball seems to still be broken.

**Comment by QuLogic** [comment] 2017-02-26 19:40
OK, I figured this out. Firstly, `cloudpickle` does a bit of weird thing and pickles `tests.something`, so the top-level needs to be in `PYTHONPATH`. This is weird because the `cloudpickle` directory is also there, so you might test _that_ instead of the installed version.

Second, the "special" file tests don't work with pytest unless you disable its capturing mode with `-s`. This is in `tox.ini`, so that might be why that works but plain `pytest` doesn't.

**Comment by ogrisel** [comment] 2017-12-05 09:16
I cannot reproduce this either. Running `pytest` (without the -s flag) in the top level folder works for me. I also took care to uninstall cloudpickle from my venv.

**Comment by ogrisel** [comment] 2017-12-05 09:19
Closing for now, please feel free to reopen with detailed info to reproduce (pytest version, with or without venv, with or without installed cloudpickle and which version...).

**Closed by ogrisel** 2017-12-05 09:19 UTC
